export const BUSINESS_CATEGORIES = [
  "Accountants",
  "Ad Agencies",
  "Appliance, Repair",
  "Appliance, Retail",
  "Arts and Crafts",
  "Arts and Entertainment - Bands, Concerts",
  "Arts and Entertainment - Banquet Halls, Venues, Event Centers",
  "Arts and Entertainment - Batting Cages, Go-Karts, Mini Golf",
  "Arts and Entertainment - Casinos",
  "Arts and Entertainment - Festivals, Fairs, Galas",
  "Arts and Entertainment - Fireworks",
  "Arts and Entertainment - Fun Centers, Trampoline Parks, Escape Rooms",
  "Arts and Entertainment - Movies, Theaters",
  "Arts and Entertainment - Museums",
  "Arts and Entertainment - Other",
  "Arts and Entertainment - Parks, Recreation",
  "Attorneys, Lawyers",
  "Bagels",
  "Bakeries, Donuts",
  "Banks, Credit Unions",
  "Batteries",
  "Beer, Liquor, Wine",
  "Bicycles",
  "Bookstores, Comics",
  "Bowling",
  "Business to Business",
  "Car, Truck, and Auto - Body",
  "Car, Truck, and Auto - Dealers",
  "Car, Truck, and Auto - Gas, Marts, Stations",
  "Car, Truck, and Auto - Oil Change",
  "Car, Truck, and Auto - Other",
  "Car, Truck, and Auto - Rentals",
  "Car, Truck, and Auto - Repair",
  "Car, Truck, and Auto - Supplies, Parts",
  "Car, Truck, and Auto - Tires",
  "Car, Truck, and Auto - Towing",
  "Car, Truck, and Auto - Transmissions",
  "Car, Truck, and Auto - Used Cars",
  "Car, Truck, and Auto - Used Parts, Salvage Yards",
  "Car, Truck, and Auto - Wash",
  "Carpet Cleaning, Restoration",
  "Cellular, Accessories, Pagers, Service, Stores",
  "Cemeteries, Cremation",
  "Chambers of Commerce",
  "Charities, Nonprofit",
  "Childcare, Daycare",
  "Clothing - Clothes, Fashion",
  "Clothing - Embroidery",
  "Clothing - Tailors, Seamstresses",
  "Community and Government",
  "Computers",
  "Construction, Builders, Architects",
  "Consumers",
  "Dance, Gymnastics",
  "Dentists, Orthodontists",
  "Dry Cleaners",
  "Education - Colleges and Universities, Adult",
  "Education - Preschool, K-12",
  "Electricians",
  "Electronics",
  "Financial, Investments",
  "Firearms, Fishing, Ammo",
  "Fitness",
  "Florists",
  "Food, Restaurants - Asian",
  "Food, Restaurants - Barbecue",
  "Food, Restaurants - Bars, Grills",
  "Food, Restaurants - Buffet",
  "Food, Restaurants - Cafe",
  "Food, Restaurants - Catering",
  "Food, Restaurants - Coffee",
  "Food, Restaurants - Deli",
  "Food, Restaurants - Family, Dining",
  "Food, Restaurants - Fast",
  "Food, Restaurants - French",
  "Food, Restaurants - Indian",
  "Food, Restaurants - Juicers, Smoothies",
  "Food, Restaurants - Mexican",
  "Food, Restaurants - Other",
  "Food, Restaurants - Pizza, Italian",
  "Food, Restaurants - Seafood",
  "Food, Restaurants - Steak House",
  "Food, Restaurants - Sushi",
  "Food, Restaurants - Thai",
  "Framing",
  "Funeral Homes",
  "Furniture, Stores",
  "Furniture, Upholstery",
  "Gifts, Card Shops, Party Supplies",
  "Golf",
  "Grocers, Grocery, Markets",
  "Hair, Skin, Nails",
  "Hardware",
  "Health - Food Stores",
  "Health - Other",
  "Health - Supplements",
  "Heating and Cooling",
  "Hobby Stores, Toy Stores",
  "Home Improvement - Bathrooms",
  "Home Improvement - Carpet, Flooring",
  "Home Improvement - Chimneys",
  "Home Improvement - Decks, Patios",
  "Home Improvement - Doors, Windows",
  "Home Improvement - Driveways",
  "Home Improvement - Fencing",
  "Home Improvement - Kitchens",
  "Home Improvement - Other",
  "Home Improvement - Remodel, Painters",
  "Home Improvement - Roofing",
  "Home Improvement - Siding",
  "Hotels",
  "Housewares",
  "Ice Cream, Candy, Yogurt",
  "Independent Sales Consultants",
  "Insurance",
  "Interiors - Blinds",
  "Interiors - Carpet, Flooring",
  "Interiors - Lighting, Fixtures",
  "Interiors - Wallpaper",
  "Internet, Networking, Service",
  "Jewelers",
  "Jobs, Job Openings",
  "Landscaping, Lawn, Tree Service",
  "Lawn, Garden Centers, Nurseries",
  "Lawn, Mowers, Shops",
  "Libraries",
  "Lighting Fixtures",
  "Limo, Taxi Service, Public Transportation",
  "Locksmiths",
  "Maid Service, House Cleaning, Window Cleaning",
  "Marine, Boats, Service",
  "Martial Arts",
  "Medical, Physicians and Doctors - Anesthesiologists",
  "Medical, Physicians and Doctors - Audiologists, Hearing",
  "Medical, Physicians and Doctors - Cardiologists",
  "Medical, Physicians and Doctors - Chiropractors",
  "Medical, Physicians and Doctors - Dermatologists",
  "Medical, Physicians and Doctors - Ear, Nose, Throat",
  "Medical, Physicians and Doctors - Family Medicine",
  "Medical, Physicians and Doctors - Health Services",
  "Medical, Physicians and Doctors - Home Health Care",
  "Medical, Physicians and Doctors - Hospital, Health Centers, Urgent Care",
  "Medical, Physicians and Doctors - Internal Medicine",
  "Medical, Physicians and Doctors - Massage Clinics, Therapists, Spas",
  "Medical, Physicians and Doctors - Mental Health, Counseling, Psychologists",
  "Medical, Physicians and Doctors - OBGYN",
  "Medical, Physicians and Doctors - Oncologists",
  "Medical, Physicians and Doctors - Ophthalmologists",
  "Medical, Physicians and Doctors - Orthopedics",
  "Medical, Physicians and Doctors - Other",
  "Medical, Physicians and Doctors - Pediatricians",
  "Medical, Physicians and Doctors - Podiatrists",
  "Medical, Physicians and Doctors - Sports Medicine",
  "Mortgages, Loans",
  "Music, Lessons",
  "Music, Stores",
  "Newspapers, Radio, Television Stations",
  "Nursing Homes/Hospice",
  "Optical, Optometrist",
  "Packaging, Shipping",
  "Personal Care Services",
  "Pest Control",
  "Pets - Boarding, Day Care",
  "Pets - Feed, Products",
  "Pets - Other",
  "Pets - Services, Grooming",
  "Pets - Shops",
  "Pets - Veterinarians",
  "Pharmacies",
  "Photography, Processing, Cameras",
  "Plumbing",
  "Political",
  "Pools",
  "Powersports, Motorcycles, Scooters, Utes",
  "Propane, Propane Refills, Accessories",
  "Real Estate - Agents",
  "Real Estate - Apartments, Condos",
  "Real Estate - Commercial",
  "Real Estate - Inspection",
  "Real Estate - Mobile Homes",
  "Real Estate - Movers",
  "Real Estate - Other",
  "Real Estate - Property Management",
  "Religious - Churches, Synagogues, Mosques",
  "Rentals, Equipment, Tools",
  "Resale, Pawn Shops, Consignment",
  "Retirement Homes, Assisted Living",
  "Security, Home Automation",
  "Senior Citizen Services",
  "Septic, Sewers",
  "Shoes",
  "Shopping - Children's Stores",
  "Shopping - Department Stores, Retail Stores",
  "Shopping - Other",
  "Shopping - Shopping Centers, Malls",
  "Shopping - Wedding, Bridal",
  "Sporting Goods",
  "Sports Teams, Clubs",
  "Storage",
  "Tanning",
  "Television - Cable",
  "Television - Sales, Repair",
  "Tobacco, CBD",
  "Tourism, Travel - Agents",
  "Tourism, Travel - Airlines, Airports",
  "Tourism, Travel - Cruises",
  "Tourism, Travel - Historical Places",
  "Tourism, Travel - Other",
  "Tourism, Travel - Resorts, Spas",
  "Tourism, Travel - Vacation Rentals",
  "Tourism, Travel - Wineries, Vineyards",
  "Town Planner Publisher",
  "Unclassified, Miscellaneous",
  "Utilities",
  "Video Rental",
  "Waste Management - Other",
  "Waste Management - Recycling",
  "Waste Management - Trash",
  "Water Treatment, Softeners, Systems",
  "Weight Loss",
] as const;

export type BusinessCategory = (typeof BUSINESS_CATEGORIES)[number];
